# Copyright (c) 2021,2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

_ansible_bender: 
  base_image: quay.io/centos/centos:centos7
  target_image:
    name: localhost/mafalb/centos7
    labels:
      'org.opencontainers.image.title': 'CentOS 7 Base Image plus updates'
      'org.label-schema.name': 'CentOS 7 Base Image plus updates'
      'org.opencontainers.image.vendor': 'Markus Falb'
      'org.label-schema.vendor': 'Markus Falb'
      'org.label-schema.build-date': "20220716"
      'org.opencontainers.image.created': '2022-07-16T18:26:15Z'
  layering: false

...
