# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: dispatch child images
  hosts: localhost
  vars_files: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') + '/imagetree.yml' }}"
  tasks:

    - name: dispatch all childs
      debug:
        msg: "dispatch {{ os }}-{{ item }}"
      loop: "{{ images[os][flavor] }}"
      when:
        - build_dependents

    - name: dispatch build
      ansible.builtin.uri:
        url: https://api.github.com/repos/mafalb/ansible-collection-containerimages/actions/workflows/BUILD.yml/dispatches
        method: POST
        headers:
          Accept: application/vnd.github.v3+json"
          Authorization: token {{ registry_token }}
        body_format: json
        body: |
          ref: {{ github_ref }}
          inputs:
            os: {{ os }}
            flavor: {{ flavor }}
            build_descendants: true
      loop: "{{ images[os][flavor] }}"
      when:
        - build_dependents
        - "{{ lookup('env','GITHUB_ACTIONS',default='false') }}"

... 
