# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Dispatch child images
  hosts: localhost
  vars_files: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') + '/imagetree.yml' }}"
  tasks:

    - name: Dispatch all childs
      ansible.builtin.debug:
        msg: "dispatch {{ os }}-{{ item }}"
      loop: "{{ (images[os] | selectattr('flavor', 'equalto', flavor))[0]['children'] | default([]) }}"
      when:
        - build_dependents

    - name: Dispatch build
      ansible.builtin.uri:
        url: https://api.github.com/repos/mafalb/ansible-collection-containerimages/actions/workflows/BUILD.yml/dispatches
        method: POST
        status_code: [204]
        headers:
          Accept: application/vnd.github.v3+json"
          Authorization: token {{ github_pat }}
        body_format: json
        body:
          ref: "{{ github_ref }}"
          inputs:
            os: "{{ os }}"
            flavor: "{{ item }}"
            build_dependents: "true"
      register: _api_call
      loop: "{{ (images[os] | selectattr('flavor', 'equalto', flavor))[0]['children'] | default([]) }}"
      when:
        - build_dependents
        - "lookup('env','GITHUB_ACTIONS',default='false')"

    - name: Debug 
      ansible.builtin.debug:
        var: _api_call

... 
