# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: publish the image
  hosts: localhost
  tasks:

    - name: login to the registry
      containers.podman.podman_login:
        username: "{{ registry_user }}"
        password: "{{ registry_token }}"
        registry: "{{ registry }}"

    # does not work
    # https://github.com/containers/ansible-podman-collections/issues/218
    - name: push the image
      when: false
      containers.podman.podman_image:
        name: localhost/{{ registry_user }}/{{ os }}-{{ flavor }}:latest
        pull: false
        push: true
        push_args:
          dest: "{{ registry }}/{{ registry_user }}/{{ os }}-{{ flavor }}:latest"

    - name: push the image
      command: ansible-bender push {{ registry }}/{{ registry_user }}/{{ os }}-{{ flavor }}

... 
