# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Publish the image
  hosts: localhost
  vars:
    container_tag: "\
      {{ ansible_date_time.year }}\
      {{ ansible_date_time.month }}\
      {{ ansible_date_time.day }}-\
      {{ ansible_date_time.hour }}\
      {{ ansible_date_time.minute }}"

  tasks:

    - name: Login to the registry
      containers.podman.podman_login:
        username: "{{ registry_user }}"
        password: "{{ registry_token }}"
        registry: "{{ registry }}"

    # does not work
    # https://github.com/containers/ansible-podman-collections/issues/218
    - name: Push the image
      when: false
      containers.podman.podman_image:
        name: localhost/{{ registry_user }}/{{ os }}-{{ flavor }}:latest
        pull: false
        push: true
        push_args:
          dest: "{{ registry }}/{{ registry_user }}/{{ os }}-{{ flavor }}:latest"

    - name: Push the image  # noqa: no-changed-when
      ansible.builtin.command:
        cmd: podman push localhost/{{ registry_user }}/{{ os }}-{{ flavor }}:latest {{ registry }}/{{ registry_user }}/{{ os }}-{{ flavor }}:{{ container_tag }}
      register: _push_output
    - name: Debug
      ansible.builtin.debug:
        var: _push_output

    - name: Push the image  # noqa: no-changed-when
      ansible.builtin.command:
        cmd: podman push localhost/{{ registry_user }}/{{ os }}-{{ flavor }}:latest {{ registry }}/{{ registry_user }}/{{ os }}-{{ flavor }}:latest
      register: _push_output
    - name: Debug
      ansible.builtin.debug:
        var: _push_output

... 
