# vim: set ft=yaml ts=2 expandtab:
---

- name: get OS specific variables
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"

- name: yum plugins are enabled
  lineinfile:
    path: /etc/yum.conf
    line: plugins=1
    regexp: '^plugins='
    backup: true
  when: yum_needs_plugin|default(false)|bool

- name: required packages are present
  package:
    name: "{{ packages }}"

- name: find unneeded systemd files
  find:
    paths:
    - /lib/systemd/system/sockets.target.wants
    patterns:
    - '*udev*'
    - '*initctl*'
    file_type: link
  register: _unneeded_files_1

- name: find unneeded systemd files
  find:
    paths:
    - /lib/systemd/system/sysinit.target.wants
    - /lib/systemd/system/multi-user.target.wants
    - /lib/systemd/system/local-fs.target.wants
    - /lib/systemd/system/basic.target.wants
    - /lib/systemd/system/anaconda.target.wants
    file_type: link
    excludes:
    - systemd-tmpfiles-setup.service
    - systemd-user-sessions.service
  register: _unneeded_files_2

- name: unneeded systemd files are absent
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ _unneeded_files_1.files }} + {{ _unneeded_files_2.files }}"

...
