# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
dependency:
  name: galaxy
  options:
    role-file: /dev/null
    requirements-file: molecule/default/requirements.yml
#lint:
#  ansible-lint -v
driver:
  name: podman
platforms:
  - name: ci
    image: ${CI_IMAGE}
provisioner:
  name: ansible
verifier:
  name: ansible
...
