# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: verify systemd
  hosts: systemd_group
  tasks:

    - name: systemd is running without errors  # noqa: command-instead-of-module
      command: systemctl is-system-running
      changed_when: false

    - name: sshd is running
      service:
        name: sshd
        state: started

- name: verify all
  hosts: ci_group
  order: sorted
  vars_files: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') + '/imagetree.yml' }}"

  handlers:
    - name: dispatch build
      ansible.builtin.uri:
        url: https://api.github.com/repos/mafalb/ansible-collection-containerimages/actions/workflows/BUILD.yml/dispatches
        method: POST
        headers:
          Accept: application/vnd.github.v3+json"
          Authorization: token {{ registry_token }}
        body_format: json
        body:
          ref: "{{ github_ref }}"
          inputs:
            os: "{{ os }}"
            flavor: "{{ flavor }}"
            build_dependents: "true"
      loop: "{{ images[os][flavor] }}"
      when:
        - build_dependents
        - "lookup('env','GITHUB_ACTIONS',default='false')"

  tasks:

    # do not fail it as this point
    # do a dispatch first
    - name: all updates are installed  # noqa: package-latest
      ansible.builtin.package:
        name: '*'
        state: latest
      register: _updates
      check_mode: true
      notify: dispatch build

- name: verify all
  hosts: ci_group
  order: sorted
  vars_files: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') + '/imagetree.yml' }}"
  tasks:
    # fail it now that a build is dispatched
    - name: assertions
      assert:
        msg: "Not all available updates are installed in this image"
        that:
          - not _updates.changed

... 
