# vim: set ft=yaml ts=2 expandtab:
---

- name: converge containerimages
  hosts: ci
  vars:
    ci_name: "{{ lookup('env','CI_NAME') }}"
    ci_image: "{{ lookup('env','CI_IMAGE') }}"
  roles:
  - role: mafalb.containerimages.cleanup

...
