# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Converge
  hosts: all
  handlers:
    - name: build the container
      make:
        chdir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        target: "{{ lookup('env', 'CI_TARGET') }}"
  tasks:
    - name: build image if necessary
      ansible.builtin.package:
        name: '*'
        state: latest
      check_mode: true
      notify: build the container

...
