# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Converge
  hosts: all
  tasks:
    - name: all updates are installed
      ansible.builtin.package:
        name: '*'
        state: latest
      check_mode: true
      notify: build the container
...
