# vim: set ft=yaml ts=2 expandtab:
---

- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

  - name: instances are destroyed  # noqa no-changed-when 301
    command: buildah rm {{ item.name }}
    loop: "{{ molecule_yml.platforms }}" 
    register: buildahs

    # Mandatory configuration for Molecule to function.

  - name: Populate instance config
    set_fact:
      instance_conf: {}

  - name: Dump instance config
    copy:
      content: |
        # Molecule managed

        {{ instance_conf | to_json | from_json | to_yaml }}
      dest: "{{ molecule_instance_config }}"
      mode: "0644"
#    when: buildahs.changed | default(false) | bool
