---
dependency:
  name: galaxy
  options:
    role-file: /dev/null
    requirements-file: molecule/build/requirements.yml
driver:
  name: podman
platforms:
  - name: ci
    image: ${CI_IMAGE}
    prebuild: true
provisioner:
  name: ansible
verifier:
  name: ansible
