# vim: set ft=yaml ts=2 expandtab:
---

- name: create a buildah instance
  hosts: localhost

  module_defaults:
    shell:
      executable: /bin/bash

  vars:
    ci_name: "{{ lookup('env','CI_NAME') }}"
    ci_image: "{{ lookup('env','CI_IMAGE') }}"
    python_pkg:
      debian9: python

  tasks:

  - name: buildah instance is created  # noqa no-changed-when 301
    command: buildah --name ci-{{ ci_name }} from {{ ci_image }}

  - name: python is present  # noqa no-changed-when 301
    shell: |
      buildah run ci-{{ ci_name }} bash -c "apt update &&
        apt-get install -y {{ python_pkg[ci_name]|default('python3') }}"
    when:
    - ci_name is match("ubuntu") or ci_name is match("debian")

...
