# vim: set ft=yaml ts=2 expandtab:
---

- name: verify
  hosts: ci

  tasks:

  - name: get installed packages
    package_facts:

  - name: python 2 is installed
    assert:
      that:
      - 'python2' in ansible_facts.packages
      - 'python3' not in ansible_facts.packages
    when: ansible_inventory_host in ['ci-debian9','ci-centos7']

  - name: python 3 is installed
    assert:
      that:
      - 'python3' in ansible_facts.packages
    when: ansible_inventory_host not in ['ci-debian9','ci-centos7']

...
