# Copyright (c) 2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: Verify systemd
  hosts: systemd_group
  tasks:

    - name: Systemd is running without errors  # noqa: command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      changed_when: false

    - name: Sshd is running
      ansible.builtin.service:
        name: sshd
        state: started


- name: Verify all
  hosts: ci_group
  order: sorted
  vars_files: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') + '/imagetree.yml' }}"

  tasks:

    - name: All updates are installed  # noqa: package-latest
      ansible.builtin.package:
        name: '*'
        state: latest
      register: _updates
      check_mode: true

    - name: Assertions
      ansible.builtin.assert:
        msg: "Not all available updates are installed in this image"
        that:
          - not _updates.changed
          - github_workflow == 'CI'

... 
