# vim: set ft=yaml ts=2 expandtab:
---

packages:
- file
- which
- sudo
- iproute
- systemd

packages_to_remove:
- NetworkManager*

systemd_masked:
- kdump.service
- auditd.service
# Failed to create listening socket (audit 1): Operation not permitted
- systemd-journald-audit.socket


...
