# vim: set ft=yaml ts=2 expandtab:
---

driver:
  name: docker

platforms:
- name: ci-${CI_NAME-ci-rocky8}
  image: ${CI_IMAGE:-localhost/systemd/rocky8}
  command: /lib/systemd/systemd
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  capabilities:
  - SYS_ADMIN
  privileged: true
  pre_build_image: true
  tty: true
  groups:
  - ci_group

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
