# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

  
- name: converge containerimages
  hosts: all
  vars:
    ansible_bender:
      base_image: "{{ lookup('env', 'CI_IMAGE') }}"
      target_image:
        name: "{{ lookup('env', 'CI_HOSTNAME') }}"
        labels:
          'org.opencontainers.image.title': "Systemd Image"

  tasks:
    - name: all packages are updated
      package:
        name: "*"
        state: latest

...
