# vim: set ft=yaml ts=2 expandtab:
---

galaxy_info:
  author: Markus Falb <markus.falb@mafalb.at>
  description: Ansible role mafalb.containerimages.cleanup
  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"

  galaxy_tags:
    - linux
    - infrastructure

dependencies: []

...
