# vim: set ft=yaml ts=2 expandtab:
---

name: BUILD

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      os:
        description: an os, e.g. centos7
        required: true
      flavor:
        description: the flavor, e.g. base or systemd
        required: true

jobs:

  build_image:

    runs-on: ubuntu-20.04

    env:
      CI_NAME: "${{ github.event.inputs.os }}"
      CI_TARGET: "${{ github.event.inputs.os }}-${{ github.event.inputs.flavor }}"
      FORCE_BUILD: true
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/containerimages

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: build image
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          ansible-galaxy collection install containers.podman -p playbooks/collections
          make $CI_TARGET

      - name: debug
        run: |
          podman images
          podman inspect localhost/mafalb/$CI_TARGET

      - name: verify image
        run:
          source ~/.virtualenvs/ci-tools/bin/activate
          CI_IMAGE=localhost/mafalb/$CI_TARGET molecule test

...
