# vim: set ft=yaml ts=2 expandtab:
---

name: BUILD

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:

  BUILD:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:

        flavor:
          - base
          - systemd

        os:
          - centos7
          - fedora36

    env:
      CI_NAME: ${{ matrix.os }}
      CI_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}.${{ matrix.flavor }}:latest"
      CI_CONTAINER: "${{ matrix.os }}-${{ matrix.flavor }}"
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/containerimages

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: build images
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          make ${{ matrix.os }}-${{ matrix.flavor }}

...
