# vim: set ft=yaml ts=2 expandtab:
---

name: CHECK

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '40 15 * * 6'

jobs:

  build_image:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:

        flavor:
          - base
          - systemd

        os:
          - centos7
          - fedora36

    env:
      CI_NAME: "${{ matrix.os }}"
      CI_FLAVOR: "${{ matrix.flavor }}"
      CI_TARGET: "${{ matrix.os }}-${{ matrix.flavor }}"
      CI_IMAGE: "ghcr.io/${{ github.actor }}/${{ matrix.os }}-${{ matrix.flavor }}:latest"
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/containerimages

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: pull container images
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman pull $CI_IMAGE

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: debug
        run: |
          podman images
          podman inspect $CI_IMAGE

      - name: verify image
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          molecule test

...
