# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
  pull_request_review:

jobs:

  ci:

    # don't run on pull request from ourselves
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:

        flavor:
          - base
          - systemd

        os:
          - centos7
          #- fedora36

    env:
      CI_NAME: ${{ matrix.os }}
      CI_TARGET: "${{ matrix.os }}-${{ matrix.flavor }}"
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/containerimages

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: lint
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          bash tests/lint.sh

      - name: build image
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          ansible-galaxy collection install containers.podman -p playbooks/collections
          make $CI_TARGET

      - name: debug
        run: |
          podman images
          podman inspect localhost/mafalb/$CI_TARGET

      - name: run tests
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          CI_IMAGE=localhost/mafalb/$CI_TARGET molecule test

...
