# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy

  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:

  CHECK:

    # don't run on pull request from ourselves
    #     #
    #         if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:

        flavor:
          - base
          - systemd

        os:
          - centos7
          - fedora36

    env:
      CI_NAME: ${{ matrix.os }}
      CI_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}-${{ matrix.flavor }}:latest"
      CI_CONTAINER: "${{ matrix.os }}-${{ matrix.flavor }}"
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/containerimages

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: pull container images
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman pull $CI_IMAGE

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: check for updates
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          molecule test

...
