# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy

  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:

  CHECK:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

      matrix:

        os:
          - centos7
          - fedora36

        flavor:
          - updates
          - systemd

    env:

      CI_NAME: ${{ matrix.os }}
      CI_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}.${{ matrix.flavor }}:latest"
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:

      - name: pull container image
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          podman pull $CI_IMAGE

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages

      - name: install necessary tools into a python virtualenv
        run: |
          make tools

      - name: check for updates
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          molecule test

  BUILD:

    # the image is not up to date
    if: failure()

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

      matrix:

        target:
          - centos7
          - fedora36

    steps:

      - name: checkout collection mafalb.containerimages
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/containerimages


      - name: install necessary tools
        run: |
          make tools

      - name: check for updates
        run: |
          source ~/.virtualenvs/ci-tools/bin/activate
          molecule test
...
